export const CATEGORIES = [
  "Accountants",
  "Acupuncture",
  "Adult Entertainment",
  "Advertising Agency",
  "Air Conditioning & Heating (HVAC)",
  "Airport Shuttles",
  "Alterations & Tailoring",
  "Amusement Parks",
  "Animal Shelters",
  "Antiques",
  "Apartments",
  "Appliances & Repair",
  "Aquarium Services",
  "Architects",
  "Art Classes",
  "Art Galleries",
  "Art Supplies",
  "Arts & Crafts",
  "Arts & Entertainment",
  "Attorneys",
  "Auto Body Shops",
  "Auto Detailing",
  "Auto Glass Services",
  "Auto Loan Providers",
  "Auto Parts & Supplies",
  "Auto Repair",
  "Automotive",
  "Baby Gear & Furniture",
  "Bagels",
  "Bakeries",
  "Banks & Credit Unions",
  "Barbers",
  "Bars",
  "Beauty & Spas",
  "Bed & Breakfast",
  "Beer",
  "Bicycles",
  "Boat Charters",
  "Boating",
  "Book Stores",
  "Bookkeepers",
  "Bowling",
  "Breakfast & Brunch",
  "Breweries",
  "Bridal",
  "Building Supplies",
  "Burgers",
  "Business Consulting",
  "Business Services",
  "Butcher",
  "Cabinetry",
  "Cafes",
  "Candy Stores",
  "Car Dealers",
  "Car Rental",
  "Car Wash",
  "Cards & Stationery",
  "Career Counseling",
  "Caribbean Food",
  "Carpet Cleaning",
  "Carpet Installation",
  "Caterers",
  "Cell Phone Repair",
  "Cheese Shops",
  "Chinese Food",
  "Chiropractors",
  "Churches",
  "Cleaning Services",
  "Clothing Rental",
  "Clothing Stores",
  "Coaching",
  "Cocktail Bars",
  "Coffee & Tea",
  "College & University",
  "Comedy Clubs",
  "Commercial Real Estate",
  "Computer Repair",
  "Computers",
  "Concert Venues",
  "Construction",
  "Consulting",
  "Contractors",
  "Convenience Stores",
  "Cooking Classes",
  "Cosmetics & Beauty Supply",
  "Cosmetic Surgeons",
  "Counseling & Mental Health",
  "Couriers & Delivery",
  "Coworking Spaces",
  "CPA",
  "Crafts",
  "Cupcakes",
  "Customs Brokers",
  "Dance Clubs",
  "Dance Studios",
  "Day Spas",
  "Daycare",
  "Decks & Railing",
  "Dentists",
  "Dermatologists",
  "Desserts",
  "Diagnostic Services",
  "Diners",
  "Divorce & Family Law",
  "DJs",
  "Doctors",
  "Dog Walkers",
  "Donuts",
  "Driving Schools",
  "Dry Cleaning & Laundry",
  "Eat & Drink",
  "Education",
  "Electricians",
  "Electronics",
  "Elementary Schools",
  "Embroidery & Crochet",
  "Employment Agencies",
  "Engineering",
  "Estate Planning Law",
  "Events",
  "Event Planning",
  "Eyewear & Opticians",
  "Farmers Market",
  "Fashion",
  "Fast Food",
  "Financial Advising",
  "Financial Services",
  "Fireplace Services",
  "Fitness & Instruction",
  "Florists",
  "Food Delivery Services",
  "Food Trucks",
  "Formal Wear",
  "Framing",
  "French Food",
  "Funeral Services",
  "Furniture Stores",
  "Gas Stations",
  "General Dentistry",
  "General Litigation",
  "Gift Shops",
  "Golf",
  "Graphic Design",
  "Grocery",
  "Gutter Services",
  "Gyms",
  "Hair Extensions",
  "Hair Removal",
  "Hair Salons",
  "Handyman",
  "Hardware Stores",
  "Health & Medical",
  "Health Markets",
  "Hearing Aid Providers",
  "Herbs & Spices",
  "High Fidelity Audio Equipment",
  "Hiking",
  "Hobby Shops",
  "Home & Garden",
  "Home Cleaning",
  "Home Decor",
  "Home Health Care",
  "Home Inspectors",
  "Home Services",
  "Home Theater Installation",
  "Horse Boarding",
  "Hospitals",
  "Hotels",
  "Hotels & Travel",
  "Ice Cream & Frozen Yogurt",
  "Imported Food",
  "Indian Food",
  "Insurance",
  "Interior Design",
  "Internet Cafes",
  "Internet Service Providers",
  "Investing",
  "IT Services & Computer Repair",
  "Italian Food",
  "Janitorial Services",
  "Japanese Food",
  "Jewelry",
  "Jewelry Repair",
  "Juice Bars & Smoothies",
  "Karaoke",
  "Kids Activities",
  "Kitchen & Bath",
  "Korean Food",
  "Landscaping",
  "Language Schools",
  "Laser Tag",
  "Lawyers",
  "Leather Goods",
  "Libraries",
  "Life Coach",
  "Lighting Fixtures",
  "Limos",
  "Live Music Venues",
  "Local Services",
  "Locksmiths",
  "Logistics & Shipping",
  "Luggage",
  "Luxury Apartments",
  "Machine Shops",
  "Magicians",
  "Mailbox Centers",
  "Makeup Artists",
  "Marketing",
  "Martial Arts",
  "Masonry & Concrete",
  "Massage",
  "Massage Therapy",
  "Mattresses",
  "Meat Shops",
  "Media Production",
  "Medical Centers",
  "Medical Spas",
  "Medical Supplies",
  "Mediterranean Food",
  "Men's Clothing",
  "Mexican Food",
  "Mobile Phones",
  "Mortgage Brokers",
  "Motorcycle Dealers",
  "Motorcycle Repair",
  "Movers",
  "Movie Theaters",
  "Museums",
  "Music & DVDs",
  "Music Venues",
  "Musical Instrument Services",
  "Nail Salons",
  "Newspapers & Magazines",
  "Nightlife",
  "Non-Profit",
  "Notaries",
  "Nurseries & Gardening",
  "Nutritionists",
  "Office Cleaning",
  "Office Equipment",
  "Optometrists",
  "Orthodontists",
  "Outlet Stores",
  "Packing Services",
  "Paint Stores",
  "Painters",
  "Parking",
  "Party & Event Planning",
  "Party Equipment Rentals",
  "Patio Coverings",
  "Pawn Shops",
  "Pediatricians",
  "Performing Arts",
  "Personal Chefs",
  "Personal Shopping",
  "Personal Trainers",
  "Pest Control",
  "Pet Groomers",
  "Pet Services",
  "Pet Sitting",
  "Pet Stores",
  "Pharmacy",
  "Photographers",
  "Photography Stores",
  "Physical Therapy",
  "Piercing",
  "Pilates",
  "Pizza",
  "Plumbers",
  "Podiatrists",
  "Pool & Billiards",
  "Pool Cleaners",
  "Preschools",
  "Pressure Washers",
  "Printing Services",
  "Private Investigation",
  "Private Schools",
  "Property Management",
  "Psychiatrists",
  "Psychics",
  "Psychologists",
  "Public Services & Government",
  "Pubs",
  "Quilting",
  "Radio Stations",
  "Real Estate",
  "Real Estate Agents",
  "Real Estate Services",
  "Recording Studios",
  "Religious Organizations",
  "Restaurants",
  "Retirement Homes",
  "Roofing",
  "Running",
  "Salons",
  "Sandwiches",
  "Scooter Rentals",
  "Screen Printing",
  "Security Services",
  "Seafood",
  "Self Storage",
  "Shipping Centers",
  "Shoe Repair",
  "Shoe Stores",
  "Shopping",
  "Signmaking",
  "Skating Rinks",
  "Skin Care",
  "Social Clubs",
  "Solar Installation",
  "Souvenir Shops",
  "Spas",
  "Specialty Food",
  "Sporting Goods",
  "Sports Clubs",
  "Steakhouses",
  "Storage",
  "Summer Camps",
  "Surf Shops",
  "Sushi Bars",
  "Swimming Lessons",
  "Swimming Pools",
  "Tanning Salons",
  "Tattoo",
  "Tax Services",
  "Taxis",
  "Tea Rooms",
  "Thai Food",
  "Therapists",
  "Thrift Stores",
  "Tires",
  "Toy Stores",
  "Tours",
  "Towing",
  "Transmission Repair",
  "Transportation",
  "Travel Agents",
  "Travel Services",
  "Tree Services",
  "Tutoring Centers",
  "Tuxedos",
  "TV Mounting",
  "Uniforms",
  "Used Bookstores",
  "Used Car Dealers",
  "Utilities",
  "Vacation Rentals",
  "Vegan Restaurants",
  "Vegetarian Restaurants",
  "Veterinarians",
  "Video Game Stores",
  "Vietnamese Food",
  "Vintage & Consignment",
  "Vocational & Technical School",
  "Waxing",
  "Web Design",
  "Wedding Planning",
  "Weight Loss Centers",
  "Wholesale Stores",
  "Wine Bars",
  "Wine Tours",
  "Women's Clothing",
  "Yoga",
  "Youth Programs",
  "Zoos",
];
