export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const POPULAR_CITIES = [
  "Abu Dhabi",
  "Accra",
  "Addis Ababa",
  "Ahmedabad",
  "Algiers",
  "Amman",
  "Amsterdam",
  "Ankara",
  "Athens",
  "Atlanta",
  "Auckland",
  "Austin",
  "Baghdad",
  "Bali",
  "Bangalore",
  "Bangkok",
  "Barcelona",
  "Beijing",
  "Beirut",
  "Belgrade",
  "Bengaluru",
  "Berlin",
  "Bogota",
  "Boston",
  "Brasilia",
  "Brisbane",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Calgary",
  "Cape Town",
  "Caracas",
  "Casablanca",
  "Charlotte",
  "Chennai",
  "Chicago",
  "Colombo",
  "Copenhagen",
  "Dallas",
  "Damascus",
  "Dar es Salaam",
  "Delhi",
  "Denver",
  "Detroit",
  "Dhaka",
  "Dubai",
  "Dublin",
  "Edinburgh",
  "Edmonton",
  "Frankfurt",
  "Geneva",
  "Glasgow",
  "Greater Noida",
  "Guangzhou",
  "Gurgaon",
  "Gurugram",
  "Hamburg",
  "Hanoi",
  "Havana",
  "Helsinki",
  "Ho Chi Minh City",
  "Hong Kong",
  "Honolulu",
  "Houston",
  "Hyderabad",
  "Indianapolis",
  "Islamabad",
  "Istanbul",
  "Jaipur",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Johannesburg",
  "Kampala",
  "Karachi",
  "Kathmandu",
  "Kiev",
  "Kigali",
  "Kingston",
  "Kolkata",
  "Kuala Lumpur",
  "Kuwait City",
  "Kyoto",
  "Lagos",
  "Lahore",
  "Las Vegas",
  "Lima",
  "Lisbon",
  "London",
  "Los Angeles",
  "Lucknow",
  "Luxembourg",
  "Madrid",
  "Manchester",
  "Manila",
  "Marrakesh",
  "Marseille",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Minneapolis",
  "Minsk",
  "Monaco",
  "Montevideo",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Nairobi",
  "Nashville",
  "New Delhi",
  "New Orleans",
  "New York",
  "Noida",
  "Oklahoma City",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Panama City",
  "Paris",
  "Perth",
  "Philadelphia",
  "Phoenix",
  "Phnom Penh",
  "Portland",
  "Prague",
  "Pune",
  "Quito",
  "Rabat",
  "Reykjavik",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "Saint Petersburg",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Santiago",
  "Sao Paulo",
  "Seattle",
  "Seoul",
  "Shanghai",
  "Shenzhen",
  "Singapore",
  "Sofia",
  "Stockholm",
  "Surat",
  "Sydney",
  "Taipei",
  "Tashkent",
  "Tehran",
  "Tel Aviv",
  "Tokyo",
  "Toronto",
  "Tunis",
  "Valencia",
  "Vancouver",
  "Vienna",
  "Vilnius",
  "Warsaw",
  "Washington",
  "Wellington",
  "Zagreb",
  "Zurich",
];

export const LOCATIONS = Array.from(
  new Set([...POPULAR_CITIES, ...COUNTRIES])
).sort((a, b) => a.localeCompare(b));
